### ISSUE TITLE
Feature: User Profile

### ISSUE THREAD

**Issue by ervinCodes** [ervinCodes/gainz-hub#13]
# Epic Title

Feature: User Profile

## Epic Description

This Feature will be for design implementation on the Profile Page which will then have access to the Post, Workouts & Feed page with authentication.

## List of Tasks (Complete in order)

1. [Task 1: Profile Page](https://github.com/ervinCodes/gainz-hub/issues/14)
2. [ ] [Task 2: Post Page](https://github.com/ervinCodes/gainz-hub/issues/16)
3. [ ] [Task 3: Workouts Page](https://github.com/username/repository-name/issues/3)
4. [ ] [Task 4: Feed Page](https://github.com/username/repository-name/issues/4)
